spring:
  application:
    name: myzstu-robot
  profiles:
    active: dev
simbot:
  core:
    bots: xxx:xxx
    scan-package: club.zstuca.myzstu.robot.listener
    tips:
      enable: false
    logo:
      enable: false